### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by lpozo**
I try to improve the code to meet PEP 8 and some other improvements.

### CODE REVIEW

**Comment by lpozo** [comment]
Ok, I'll check it up

**Comment by lpozo** [comment]
Ok, I take a look at the code, and here is my contribution

**Comment by zdenop** [comment]
Now it seems fine!

**Comment by DoTheEvo** [comment]
Thanks!

**Comment by lpozo** [comment]
ok, you are welcome. I'll be around.

**Pull request merged**
